apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodeselectortest
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
  nodeSelector:
    environment: dev

