apiVersion: v1
kind: Pod
metadata:
  name: nginx-nodename
spec:
  nodeName: minikube-m03 # schedule pod to specific node
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent

